version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

    #  build the application image
     - run: docker build -t  punktapl/helloworld-gke .

     - run: echo f06d4bff30be5318288c | docker login -u punktapl --password-stdin

    #  deploy the image
     - run: docker push punktapl/helloworld-gke